name: Build Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with: 
          args: aca-framework/app/Main.lhs -f markdown+lhs -t html -s -o docs/app/Main.html
      - uses: actions/upload-artifact@main
        with:
          path: docs/app
